stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."

test:
  stage: test
  script:
    - echo "Running tests..."


deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_MESSAGE == "Lancement de la version live"'
