stages:
  - test
  - build
  - deploy


test:
  stage: test
  script:
    - echo "Exécution des tests..."
  only:
    - main
  tags:
    - docker

build:
  stage: build
  script:
    - echo "Construction en cours..."
  only:
    - main
  tags:
    - docker

deploy_staging:
  stage: deploy
  script:
    - echo "Déploiement sur l'environnement de staging en cours..."
  only:
    - main


deploy_production:
  stage: deploy
  script:
    - echo "Déploiement sur l'environnement de production en cours..."
  only:
    - main
  when: manual

