stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Exécution des tests..."
    - run_tests.sh
  only:
    - main
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Déploiement en cours..."
    - deploy.sh
  only:
    - main
  tags:
    - docker