stages:
  - test

test:
  stage: test
  script:
    - echo "Exécution des tests..."
    # - run_tests.sh
  only:
    - main
  tags:
    - docker

deploy:
  stage: test
  script:
    - echo "Déploiement en cours..."
    # - deploy.sh
  only:
    - main
  tags:
    - docker
