image: docker:latest

stages:
  - build image Dockerfile

variables:
  DOCKER_USERNAME: ${{ secrets.Username }}
  DOCKER_PASSWORD: ${{ secrets.dockerMDP }}

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  stage: build

  script:
    - docker build -t your-image-name:latest .
    - docker push your-image-name:latest
