stages:
  - test
  - build
  - deploy


test:
  stage: test
  image: maven:3.9.6
  script:
    - echo "Exécution des tests..."
    - mvn -B verify
  only:
    - main

build:
  services:
    - docker
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_REPO .
    - docker save --output tmp-image.docker $DOCKER_IMAGE_REPO
  artifacts:
    paths:
      - tmp-image.docker
  only:
    - main

deploy_staging:
  services:
    - docker
  stage: deploy
  script:
    - docker load --input ./tmp-image.docker
    - docker login -u $DOCKER_HUB_EMAIL -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_IMAGE_REPO
    - docker logout
  only:
    - main


deploy_production:
  stage: deploy
  script:
    - echo "Déploiement sur l'environnement de production en cours..."
  only:
    - main
  when: manual

