name: Build and Push Docker Image

only:
  - main

jobs:
  build:
    image: docker:latest

    variables:
      DOCKER_USERNAME: ${{ secrets.Username }}
      DOCKER_PASSWORD: ${{ secrets.dockerMDP }}

    before_script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    script:
      - docker build -t your-image-name:latest .
      - docker push your-image-name:latest
