version: '3'
services:
  database:
    container_name: database
    image: postgres:16
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8056:8080"